spring:
  datasource:
    url: jdbc:postgresql://dietiestates2025v3.postgres.database.azure.com:5432/postgres?sslmode=require
    username: postgres
    password: Ciao12345
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  servlet:
    multipart:
      enabled: true
      location: ./uploads
      max-file-size: 10MB
      max-request-size: 10MB